Repository pantos-io/ci-workflows, pull requests merged in 2024-05, with the labels that each got.

#1 [PAN-1876] Initial content
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/ISSUE_REPORT.yml
  .github/ISSUE_TEMPLATE/feature_report.yml
  .github/pull_request_template.md
  .gitignore
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#2 [PAN-1868] Remove misleading reference to a project
  .github/ISSUE_TEMPLATE/ISSUE_REPORT.yml
  .github/ISSUE_TEMPLATE/feature_report.yml
Labels: bug

#3 [PAN-1866] add python shared CI
  .github/actions/install-poetry/action.yml
  .github/actions/install-python-deps/action.yml
  .github/workflows/python-ci.yml
Labels: enhancement

#4 [Pan-1866] Fix Python CI typo and improve documentation
  .github/workflows/python-ci.yml
  README.md
Labels: bug, documentation

#7 fix: cache config of poetry
  .github/actions/install-poetry/action.yml
Labels: bug

#6 [PAN-1881] Sonar Analysis as an independant workflow
  .github/workflows/python-ci.yml
  .github/workflows/sonar.yml
Labels: enhancement

#8 [PAN-1885] Spike to evaluate hardened agents
  .github/actions/install-poetry/action.yml
  .github/actions/install-python-deps/action.yml
  .github/workflows/python-ci.yml
  .github/workflows/sonar.yml
  README.md
Labels: enhancement

#9 [PAN-1889] Matrix of Python versions
  .github/actions/install-poetry/action.yml
  .github/actions/install-python-deps/action.yml
  .github/workflows/python-ci.yml
  .github/workflows/sonar.yml
Labels: enhancement
